### PR TITLE
Add Hawk platoon command post (PCP)

### PR DESCRIPTION
**Pull request by jweisner**
needed by DCS OpenBeta 1.5+

Tested in 1.5.2.48162 with test-mission.miz

### CODE REVIEW

**Comment by jweisner** [comment]
If you want to keep the Hawk consistent with the other AA systems that require only 3 crates, another approach will be needed.

**Comment by ciribob** [comment]
Thanks for the pull request! I've actually just rewritten how the whole AA system works as I didn't like all the hard coded values.

Check it here: https://github.com/ciribob/DCS-CTLD/blob/hawkFix/CTLD.lua

**Comment by ciribob** [comment]
Specifically, you now only need to add a new entry to this table for a new AA system as well as adding the crate definitions to the crate table:
https://github.com/ciribob/DCS-CTLD/blob/hawkFix/CTLD.lua#L1086

**Comment by jweisner** [comment]
That's awesome! I like the new additions. Keep up the great work.

**Pull request closed without merging**
