### PR TITLE
Allow units to CTLD by aircraft type and not only by pilot name

### PR DESCRIPTION
**Pull request by Queton1-1**
If option `ctld.addPlayerAircraftByType` true, allow units to CTLD by aircraft type (`ctld.aircraftTypeTable`) and not only by pilot name (`ctld.transportPilotNames`)

### CODE REVIEW

**Comment by davidp57** [comment]
It's a good idea; did you test with players in a non-pilot multicrew position?

**Comment by Queton1-1** [comment]
Yep, it works great.

**Review by davidp57 — COMMENTED** [review]
Hi ! Make these corrections please:
- add `local` to make your loop variables local
- correct the two occurences of this typo: missing `_` in `_match = match + 1` (would never make the count up more than to a value of one)
Did you really test? Please test.

**Comment by RexAttaque** [comment]
Opened a pull request with a cleaned up code, hasn't been tested in MP or with mods, at least on my end.

**Comment by RexAttaque** [comment]
also isn't there a way to do this at mission start ? seems terribly inefficient to do it every 10 seconds

**Comment by Queton1-1** [comment]
> also isn't there a way to do this at mission start ? seems terribly inefficient to do it every 10 seconds. Now I don't know so this will do fine.

No, as the players choppers/aircrafts don't exist before you slot into.
I agree, it's ineficient.

**Comment by RexAttaque** [comment]
> > also isn't there a way to do this at mission start ? seems terribly inefficient to do it every 10 seconds. Now I don't know so this will do fine.
> 
> No, as the players choppers/aircrafts don't exist before you slot into. I agree, it's inefficient.

Passed through MIST databases, added to the PR on your end

**Comment by Queton1-1** [comment]
Refactored script from RexAttaque works well.
Didn't see any bug in multiplayer nor solo at this time.

**Pull request merged**
